name: Continuous Integration and Deployment

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

env:
    AZURE_WEBAPP_NAME: taskify-api

jobs:
    build-and-deploy:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.x]
                mongodb-version: ['5.0.9']

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@main
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Start MongoDB
              uses: MongoCamp/mongodb-github-action@1.0.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}
            - name: Run npm clean install
              run: npm ci
            - name: Run linting and prettier check
              run: npm run lint
            - name: Run build
              run: npm run -w react-frontend build
            - name: Run test
              run: npm test
            - name: 'Deploy to Azure WebApp'
              uses: azure/webapps-deploy@v3
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
